### ISSUE TITLE
Feat : 샘플 데이터 생성

### ISSUE THREAD

**Issue by chae-hwa** [likelion-backendschool/FinalProject_LimChaeMin_team1#11]
## Description
- 샘플 데이터 생성

## Todo
- [x] 장바구니 샘플 데이터 생성
- [x] 주문 샘플 데이터 생성
- [x] 캐시 샘플 데이터 생성

## ETC
- 기타 참고 사항
